/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "Muse_v2.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(muse2_DataCollection, muse2_DataCollection, AUTO)


PB_BIND(muse2_Data, muse2_Data, AUTO)


PB_BIND(muse2_EEG, muse2_EEG, AUTO)


PB_BIND(muse2_Quantization, muse2_Quantization, AUTO)


PB_BIND(muse2_Accelerometer, muse2_Accelerometer, AUTO)


PB_BIND(muse2_Annotation, muse2_Annotation, AUTO)


PB_BIND(muse2_Battery, muse2_Battery, AUTO)


PB_BIND(muse2_Version, muse2_Version, AUTO)


PB_BIND(muse2_Config, muse2_Config, 2)


PB_BIND(muse2_EEG_DroppedSamples, muse2_EEG_DroppedSamples, AUTO)


PB_BIND(muse2_ACC_DroppedSamples, muse2_ACC_DroppedSamples, AUTO)


PB_BIND(muse2_ComputingDevice, muse2_ComputingDevice, AUTO)


PB_BIND(muse2_DSP, muse2_DSP, AUTO)


/* Definition for extension field muse2_EEG_data */
typedef struct _muse2_EEG_data_extmsg { 
    muse2_EEG data; 
} muse2_EEG_data_extmsg;
#define muse2_EEG_data_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  data,              8)
#define muse2_EEG_data_extmsg_CALLBACK NULL
#define muse2_EEG_data_extmsg_DEFAULT NULL
#define muse2_EEG_data_extmsg_data_MSGTYPE muse2_EEG
pb_byte_t muse2_EEG_data_extmsg_default[] = {0x00};
PB_BIND(muse2_EEG_data_extmsg, muse2_EEG_data_extmsg, AUTO)
const pb_extension_type_t muse2_EEG_data = {
    NULL,
    NULL,
    &muse2_EEG_data_extmsg_msg
};

/* Definition for extension field muse2_Quantization_data */
typedef struct _muse2_Quantization_data_extmsg { 
    muse2_Quantization data; 
} muse2_Quantization_data_extmsg;
#define muse2_Quantization_data_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  data,              9)
#define muse2_Quantization_data_extmsg_CALLBACK NULL
#define muse2_Quantization_data_extmsg_DEFAULT NULL
#define muse2_Quantization_data_extmsg_data_MSGTYPE muse2_Quantization
pb_byte_t muse2_Quantization_data_extmsg_default[] = {0x00};
PB_BIND(muse2_Quantization_data_extmsg, muse2_Quantization_data_extmsg, AUTO)
const pb_extension_type_t muse2_Quantization_data = {
    NULL,
    NULL,
    &muse2_Quantization_data_extmsg_msg
};

/* Definition for extension field muse2_Accelerometer_data */
typedef struct _muse2_Accelerometer_data_extmsg { 
    muse2_Accelerometer data; 
} muse2_Accelerometer_data_extmsg;
#define muse2_Accelerometer_data_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  data,             10)
#define muse2_Accelerometer_data_extmsg_CALLBACK NULL
#define muse2_Accelerometer_data_extmsg_DEFAULT NULL
#define muse2_Accelerometer_data_extmsg_data_MSGTYPE muse2_Accelerometer
pb_byte_t muse2_Accelerometer_data_extmsg_default[] = {0x00};
PB_BIND(muse2_Accelerometer_data_extmsg, muse2_Accelerometer_data_extmsg, AUTO)
const pb_extension_type_t muse2_Accelerometer_data = {
    NULL,
    NULL,
    &muse2_Accelerometer_data_extmsg_msg
};

/* Definition for extension field muse2_Annotation_data */
typedef struct _muse2_Annotation_data_extmsg { 
    muse2_Annotation data; 
} muse2_Annotation_data_extmsg;
#define muse2_Annotation_data_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  data,            100)
#define muse2_Annotation_data_extmsg_CALLBACK NULL
#define muse2_Annotation_data_extmsg_DEFAULT NULL
#define muse2_Annotation_data_extmsg_data_MSGTYPE muse2_Annotation
pb_byte_t muse2_Annotation_data_extmsg_default[] = {0x00};
PB_BIND(muse2_Annotation_data_extmsg, muse2_Annotation_data_extmsg, 2)
const pb_extension_type_t muse2_Annotation_data = {
    NULL,
    NULL,
    &muse2_Annotation_data_extmsg_msg
};

/* Definition for extension field muse2_Battery_data */
typedef struct _muse2_Battery_data_extmsg { 
    muse2_Battery data; 
} muse2_Battery_data_extmsg;
#define muse2_Battery_data_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  data,            101)
#define muse2_Battery_data_extmsg_CALLBACK NULL
#define muse2_Battery_data_extmsg_DEFAULT NULL
#define muse2_Battery_data_extmsg_data_MSGTYPE muse2_Battery
pb_byte_t muse2_Battery_data_extmsg_default[] = {0x00};
PB_BIND(muse2_Battery_data_extmsg, muse2_Battery_data_extmsg, 2)
const pb_extension_type_t muse2_Battery_data = {
    NULL,
    NULL,
    &muse2_Battery_data_extmsg_msg
};

/* Definition for extension field muse2_Version_data */
typedef struct _muse2_Version_data_extmsg { 
    muse2_Version data; 
} muse2_Version_data_extmsg;
#define muse2_Version_data_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  data,            102)
#define muse2_Version_data_extmsg_CALLBACK NULL
#define muse2_Version_data_extmsg_DEFAULT NULL
#define muse2_Version_data_extmsg_data_MSGTYPE muse2_Version
pb_byte_t muse2_Version_data_extmsg_default[] = {0x00};
PB_BIND(muse2_Version_data_extmsg, muse2_Version_data_extmsg, 2)
const pb_extension_type_t muse2_Version_data = {
    NULL,
    NULL,
    &muse2_Version_data_extmsg_msg
};

/* Definition for extension field muse2_Config_data */
typedef struct _muse2_Config_data_extmsg { 
    muse2_Config data; 
} muse2_Config_data_extmsg;
#define muse2_Config_data_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  data,            103)
#define muse2_Config_data_extmsg_CALLBACK NULL
#define muse2_Config_data_extmsg_DEFAULT NULL
#define muse2_Config_data_extmsg_data_MSGTYPE muse2_Config
pb_byte_t muse2_Config_data_extmsg_default[] = {0x00};
PB_BIND(muse2_Config_data_extmsg, muse2_Config_data_extmsg, 2)
const pb_extension_type_t muse2_Config_data = {
    NULL,
    NULL,
    &muse2_Config_data_extmsg_msg
};

/* Definition for extension field muse2_EEG_DroppedSamples_data */
typedef struct _muse2_EEG_DroppedSamples_data_extmsg { 
    muse2_EEG_DroppedSamples data; 
} muse2_EEG_DroppedSamples_data_extmsg;
#define muse2_EEG_DroppedSamples_data_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  data,            202)
#define muse2_EEG_DroppedSamples_data_extmsg_CALLBACK NULL
#define muse2_EEG_DroppedSamples_data_extmsg_DEFAULT NULL
#define muse2_EEG_DroppedSamples_data_extmsg_data_MSGTYPE muse2_EEG_DroppedSamples
pb_byte_t muse2_EEG_DroppedSamples_data_extmsg_default[] = {0x00};
PB_BIND(muse2_EEG_DroppedSamples_data_extmsg, muse2_EEG_DroppedSamples_data_extmsg, 2)
const pb_extension_type_t muse2_EEG_DroppedSamples_data = {
    NULL,
    NULL,
    &muse2_EEG_DroppedSamples_data_extmsg_msg
};

/* Definition for extension field muse2_ACC_DroppedSamples_data */
typedef struct _muse2_ACC_DroppedSamples_data_extmsg { 
    muse2_ACC_DroppedSamples data; 
} muse2_ACC_DroppedSamples_data_extmsg;
#define muse2_ACC_DroppedSamples_data_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  data,            203)
#define muse2_ACC_DroppedSamples_data_extmsg_CALLBACK NULL
#define muse2_ACC_DroppedSamples_data_extmsg_DEFAULT NULL
#define muse2_ACC_DroppedSamples_data_extmsg_data_MSGTYPE muse2_ACC_DroppedSamples
pb_byte_t muse2_ACC_DroppedSamples_data_extmsg_default[] = {0x00};
PB_BIND(muse2_ACC_DroppedSamples_data_extmsg, muse2_ACC_DroppedSamples_data_extmsg, 2)
const pb_extension_type_t muse2_ACC_DroppedSamples_data = {
    NULL,
    NULL,
    &muse2_ACC_DroppedSamples_data_extmsg_msg
};

/* Definition for extension field muse2_ComputingDevice_data */
typedef struct _muse2_ComputingDevice_data_extmsg { 
    muse2_ComputingDevice data; 
} muse2_ComputingDevice_data_extmsg;
#define muse2_ComputingDevice_data_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  data,            201)
#define muse2_ComputingDevice_data_extmsg_CALLBACK NULL
#define muse2_ComputingDevice_data_extmsg_DEFAULT NULL
#define muse2_ComputingDevice_data_extmsg_data_MSGTYPE muse2_ComputingDevice
pb_byte_t muse2_ComputingDevice_data_extmsg_default[] = {0x00};
PB_BIND(muse2_ComputingDevice_data_extmsg, muse2_ComputingDevice_data_extmsg, 2)
const pb_extension_type_t muse2_ComputingDevice_data = {
    NULL,
    NULL,
    &muse2_ComputingDevice_data_extmsg_msg
};

/* Definition for extension field muse2_DSP_data */
typedef struct _muse2_DSP_data_extmsg { 
    muse2_DSP data; 
} muse2_DSP_data_extmsg;
#define muse2_DSP_data_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  data,            200)
#define muse2_DSP_data_extmsg_CALLBACK NULL
#define muse2_DSP_data_extmsg_DEFAULT NULL
#define muse2_DSP_data_extmsg_data_MSGTYPE muse2_DSP
pb_byte_t muse2_DSP_data_extmsg_default[] = {0x00};
PB_BIND(muse2_DSP_data_extmsg, muse2_DSP_data_extmsg, 2)
const pb_extension_type_t muse2_DSP_data = {
    NULL,
    NULL,
    &muse2_DSP_data_extmsg_msg
};







#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

