/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "Muse_v1.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(muse1_DataCollection, muse1_DataCollection, AUTO)


PB_BIND(muse1_Data, muse1_Data, AUTO)


PB_BIND(muse1_EEG, muse1_EEG, AUTO)


PB_BIND(muse1_Quantization, muse1_Quantization, AUTO)


PB_BIND(muse1_Accelerometer, muse1_Accelerometer, AUTO)


PB_BIND(muse1_Annotation, muse1_Annotation, AUTO)


PB_BIND(muse1_Battery, muse1_Battery, AUTO)


PB_BIND(muse1_Version, muse1_Version, AUTO)


PB_BIND(muse1_Config, muse1_Config, AUTO)


/* Definition for extension field muse1_EEG_data */
typedef struct _muse1_EEG_data_extmsg { 
    muse1_EEG data; 
} muse1_EEG_data_extmsg;
#define muse1_EEG_data_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  data,              8)
#define muse1_EEG_data_extmsg_CALLBACK NULL
#define muse1_EEG_data_extmsg_DEFAULT NULL
#define muse1_EEG_data_extmsg_data_MSGTYPE muse1_EEG
pb_byte_t muse1_EEG_data_extmsg_default[] = {0x00};
PB_BIND(muse1_EEG_data_extmsg, muse1_EEG_data_extmsg, AUTO)
const pb_extension_type_t muse1_EEG_data = {
    NULL,
    NULL,
    &muse1_EEG_data_extmsg_msg
};

/* Definition for extension field muse1_Quantization_data */
typedef struct _muse1_Quantization_data_extmsg { 
    muse1_Quantization data; 
} muse1_Quantization_data_extmsg;
#define muse1_Quantization_data_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  data,              9)
#define muse1_Quantization_data_extmsg_CALLBACK NULL
#define muse1_Quantization_data_extmsg_DEFAULT NULL
#define muse1_Quantization_data_extmsg_data_MSGTYPE muse1_Quantization
pb_byte_t muse1_Quantization_data_extmsg_default[] = {0x00};
PB_BIND(muse1_Quantization_data_extmsg, muse1_Quantization_data_extmsg, AUTO)
const pb_extension_type_t muse1_Quantization_data = {
    NULL,
    NULL,
    &muse1_Quantization_data_extmsg_msg
};

/* Definition for extension field muse1_Accelerometer_data */
typedef struct _muse1_Accelerometer_data_extmsg { 
    muse1_Accelerometer data; 
} muse1_Accelerometer_data_extmsg;
#define muse1_Accelerometer_data_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  data,             10)
#define muse1_Accelerometer_data_extmsg_CALLBACK NULL
#define muse1_Accelerometer_data_extmsg_DEFAULT NULL
#define muse1_Accelerometer_data_extmsg_data_MSGTYPE muse1_Accelerometer
pb_byte_t muse1_Accelerometer_data_extmsg_default[] = {0x00};
PB_BIND(muse1_Accelerometer_data_extmsg, muse1_Accelerometer_data_extmsg, AUTO)
const pb_extension_type_t muse1_Accelerometer_data = {
    NULL,
    NULL,
    &muse1_Accelerometer_data_extmsg_msg
};

/* Definition for extension field muse1_Annotation_data */
typedef struct _muse1_Annotation_data_extmsg { 
    muse1_Annotation data; 
} muse1_Annotation_data_extmsg;
#define muse1_Annotation_data_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  data,            100)
#define muse1_Annotation_data_extmsg_CALLBACK NULL
#define muse1_Annotation_data_extmsg_DEFAULT NULL
#define muse1_Annotation_data_extmsg_data_MSGTYPE muse1_Annotation
pb_byte_t muse1_Annotation_data_extmsg_default[] = {0x00};
PB_BIND(muse1_Annotation_data_extmsg, muse1_Annotation_data_extmsg, 2)
const pb_extension_type_t muse1_Annotation_data = {
    NULL,
    NULL,
    &muse1_Annotation_data_extmsg_msg
};

/* Definition for extension field muse1_Battery_data */
typedef struct _muse1_Battery_data_extmsg { 
    muse1_Battery data; 
} muse1_Battery_data_extmsg;
#define muse1_Battery_data_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  data,            101)
#define muse1_Battery_data_extmsg_CALLBACK NULL
#define muse1_Battery_data_extmsg_DEFAULT NULL
#define muse1_Battery_data_extmsg_data_MSGTYPE muse1_Battery
pb_byte_t muse1_Battery_data_extmsg_default[] = {0x00};
PB_BIND(muse1_Battery_data_extmsg, muse1_Battery_data_extmsg, 2)
const pb_extension_type_t muse1_Battery_data = {
    NULL,
    NULL,
    &muse1_Battery_data_extmsg_msg
};

/* Definition for extension field muse1_Version_data */
typedef struct _muse1_Version_data_extmsg { 
    muse1_Version data; 
} muse1_Version_data_extmsg;
#define muse1_Version_data_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  data,            102)
#define muse1_Version_data_extmsg_CALLBACK NULL
#define muse1_Version_data_extmsg_DEFAULT NULL
#define muse1_Version_data_extmsg_data_MSGTYPE muse1_Version
pb_byte_t muse1_Version_data_extmsg_default[] = {0x00};
PB_BIND(muse1_Version_data_extmsg, muse1_Version_data_extmsg, 2)
const pb_extension_type_t muse1_Version_data = {
    NULL,
    NULL,
    &muse1_Version_data_extmsg_msg
};

/* Definition for extension field muse1_Config_data */
typedef struct _muse1_Config_data_extmsg { 
    muse1_Config data; 
} muse1_Config_data_extmsg;
#define muse1_Config_data_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  data,            103)
#define muse1_Config_data_extmsg_CALLBACK NULL
#define muse1_Config_data_extmsg_DEFAULT NULL
#define muse1_Config_data_extmsg_data_MSGTYPE muse1_Config
pb_byte_t muse1_Config_data_extmsg_default[] = {0x00};
PB_BIND(muse1_Config_data_extmsg, muse1_Config_data_extmsg, 2)
const pb_extension_type_t muse1_Config_data = {
    NULL,
    NULL,
    &muse1_Config_data_extmsg_msg
};




#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

