/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Muse_v2.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Muse_v2.pb-c.h"
void   muse2__data_collection__init
                     (Muse2__DataCollection         *message)
{
  static Muse2__DataCollection init_value = MUSE2__DATA_COLLECTION__INIT;
  *message = init_value;
}
size_t muse2__data_collection__get_packed_size
                     (const Muse2__DataCollection *message)
{
  assert(message->base.descriptor == &muse2__data_collection__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t muse2__data_collection__pack
                     (const Muse2__DataCollection *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &muse2__data_collection__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t muse2__data_collection__pack_to_buffer
                     (const Muse2__DataCollection *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &muse2__data_collection__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Muse2__DataCollection *
       muse2__data_collection__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Muse2__DataCollection *)
     protobuf_c_message_unpack (&muse2__data_collection__descriptor,
                                allocator, len, data);
}
void   muse2__data_collection__free_unpacked
                     (Muse2__DataCollection *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &muse2__data_collection__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   muse2__data__init
                     (Muse2__Data         *message)
{
  static Muse2__Data init_value = MUSE2__DATA__INIT;
  *message = init_value;
}
size_t muse2__data__get_packed_size
                     (const Muse2__Data *message)
{
  assert(message->base.descriptor == &muse2__data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t muse2__data__pack
                     (const Muse2__Data *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &muse2__data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t muse2__data__pack_to_buffer
                     (const Muse2__Data *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &muse2__data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Muse2__Data *
       muse2__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Muse2__Data *)
     protobuf_c_message_unpack (&muse2__data__descriptor,
                                allocator, len, data);
}
void   muse2__data__free_unpacked
                     (Muse2__Data *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &muse2__data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   muse2__eeg__init
                     (Muse2__EEG         *message)
{
  static Muse2__EEG init_value = MUSE2__EEG__INIT;
  *message = init_value;
}
size_t muse2__eeg__get_packed_size
                     (const Muse2__EEG *message)
{
  assert(message->base.descriptor == &muse2__eeg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t muse2__eeg__pack
                     (const Muse2__EEG *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &muse2__eeg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t muse2__eeg__pack_to_buffer
                     (const Muse2__EEG *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &muse2__eeg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Muse2__EEG *
       muse2__eeg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Muse2__EEG *)
     protobuf_c_message_unpack (&muse2__eeg__descriptor,
                                allocator, len, data);
}
void   muse2__eeg__free_unpacked
                     (Muse2__EEG *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &muse2__eeg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   muse2__quantization__init
                     (Muse2__Quantization         *message)
{
  static Muse2__Quantization init_value = MUSE2__QUANTIZATION__INIT;
  *message = init_value;
}
size_t muse2__quantization__get_packed_size
                     (const Muse2__Quantization *message)
{
  assert(message->base.descriptor == &muse2__quantization__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t muse2__quantization__pack
                     (const Muse2__Quantization *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &muse2__quantization__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t muse2__quantization__pack_to_buffer
                     (const Muse2__Quantization *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &muse2__quantization__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Muse2__Quantization *
       muse2__quantization__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Muse2__Quantization *)
     protobuf_c_message_unpack (&muse2__quantization__descriptor,
                                allocator, len, data);
}
void   muse2__quantization__free_unpacked
                     (Muse2__Quantization *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &muse2__quantization__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   muse2__accelerometer__init
                     (Muse2__Accelerometer         *message)
{
  static Muse2__Accelerometer init_value = MUSE2__ACCELEROMETER__INIT;
  *message = init_value;
}
size_t muse2__accelerometer__get_packed_size
                     (const Muse2__Accelerometer *message)
{
  assert(message->base.descriptor == &muse2__accelerometer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t muse2__accelerometer__pack
                     (const Muse2__Accelerometer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &muse2__accelerometer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t muse2__accelerometer__pack_to_buffer
                     (const Muse2__Accelerometer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &muse2__accelerometer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Muse2__Accelerometer *
       muse2__accelerometer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Muse2__Accelerometer *)
     protobuf_c_message_unpack (&muse2__accelerometer__descriptor,
                                allocator, len, data);
}
void   muse2__accelerometer__free_unpacked
                     (Muse2__Accelerometer *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &muse2__accelerometer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   muse2__annotation__init
                     (Muse2__Annotation         *message)
{
  static Muse2__Annotation init_value = MUSE2__ANNOTATION__INIT;
  *message = init_value;
}
size_t muse2__annotation__get_packed_size
                     (const Muse2__Annotation *message)
{
  assert(message->base.descriptor == &muse2__annotation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t muse2__annotation__pack
                     (const Muse2__Annotation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &muse2__annotation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t muse2__annotation__pack_to_buffer
                     (const Muse2__Annotation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &muse2__annotation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Muse2__Annotation *
       muse2__annotation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Muse2__Annotation *)
     protobuf_c_message_unpack (&muse2__annotation__descriptor,
                                allocator, len, data);
}
void   muse2__annotation__free_unpacked
                     (Muse2__Annotation *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &muse2__annotation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   muse2__battery__init
                     (Muse2__Battery         *message)
{
  static Muse2__Battery init_value = MUSE2__BATTERY__INIT;
  *message = init_value;
}
size_t muse2__battery__get_packed_size
                     (const Muse2__Battery *message)
{
  assert(message->base.descriptor == &muse2__battery__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t muse2__battery__pack
                     (const Muse2__Battery *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &muse2__battery__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t muse2__battery__pack_to_buffer
                     (const Muse2__Battery *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &muse2__battery__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Muse2__Battery *
       muse2__battery__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Muse2__Battery *)
     protobuf_c_message_unpack (&muse2__battery__descriptor,
                                allocator, len, data);
}
void   muse2__battery__free_unpacked
                     (Muse2__Battery *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &muse2__battery__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   muse2__version__init
                     (Muse2__Version         *message)
{
  static Muse2__Version init_value = MUSE2__VERSION__INIT;
  *message = init_value;
}
size_t muse2__version__get_packed_size
                     (const Muse2__Version *message)
{
  assert(message->base.descriptor == &muse2__version__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t muse2__version__pack
                     (const Muse2__Version *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &muse2__version__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t muse2__version__pack_to_buffer
                     (const Muse2__Version *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &muse2__version__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Muse2__Version *
       muse2__version__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Muse2__Version *)
     protobuf_c_message_unpack (&muse2__version__descriptor,
                                allocator, len, data);
}
void   muse2__version__free_unpacked
                     (Muse2__Version *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &muse2__version__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   muse2__config__init
                     (Muse2__Config         *message)
{
  static Muse2__Config init_value = MUSE2__CONFIG__INIT;
  *message = init_value;
}
size_t muse2__config__get_packed_size
                     (const Muse2__Config *message)
{
  assert(message->base.descriptor == &muse2__config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t muse2__config__pack
                     (const Muse2__Config *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &muse2__config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t muse2__config__pack_to_buffer
                     (const Muse2__Config *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &muse2__config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Muse2__Config *
       muse2__config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Muse2__Config *)
     protobuf_c_message_unpack (&muse2__config__descriptor,
                                allocator, len, data);
}
void   muse2__config__free_unpacked
                     (Muse2__Config *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &muse2__config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   muse2__eeg__dropped_samples__init
                     (Muse2__EEGDroppedSamples         *message)
{
  static Muse2__EEGDroppedSamples init_value = MUSE2__EEG__DROPPED_SAMPLES__INIT;
  *message = init_value;
}
size_t muse2__eeg__dropped_samples__get_packed_size
                     (const Muse2__EEGDroppedSamples *message)
{
  assert(message->base.descriptor == &muse2__eeg__dropped_samples__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t muse2__eeg__dropped_samples__pack
                     (const Muse2__EEGDroppedSamples *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &muse2__eeg__dropped_samples__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t muse2__eeg__dropped_samples__pack_to_buffer
                     (const Muse2__EEGDroppedSamples *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &muse2__eeg__dropped_samples__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Muse2__EEGDroppedSamples *
       muse2__eeg__dropped_samples__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Muse2__EEGDroppedSamples *)
     protobuf_c_message_unpack (&muse2__eeg__dropped_samples__descriptor,
                                allocator, len, data);
}
void   muse2__eeg__dropped_samples__free_unpacked
                     (Muse2__EEGDroppedSamples *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &muse2__eeg__dropped_samples__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   muse2__acc__dropped_samples__init
                     (Muse2__ACCDroppedSamples         *message)
{
  static Muse2__ACCDroppedSamples init_value = MUSE2__ACC__DROPPED_SAMPLES__INIT;
  *message = init_value;
}
size_t muse2__acc__dropped_samples__get_packed_size
                     (const Muse2__ACCDroppedSamples *message)
{
  assert(message->base.descriptor == &muse2__acc__dropped_samples__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t muse2__acc__dropped_samples__pack
                     (const Muse2__ACCDroppedSamples *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &muse2__acc__dropped_samples__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t muse2__acc__dropped_samples__pack_to_buffer
                     (const Muse2__ACCDroppedSamples *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &muse2__acc__dropped_samples__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Muse2__ACCDroppedSamples *
       muse2__acc__dropped_samples__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Muse2__ACCDroppedSamples *)
     protobuf_c_message_unpack (&muse2__acc__dropped_samples__descriptor,
                                allocator, len, data);
}
void   muse2__acc__dropped_samples__free_unpacked
                     (Muse2__ACCDroppedSamples *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &muse2__acc__dropped_samples__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   muse2__computing_device__init
                     (Muse2__ComputingDevice         *message)
{
  static Muse2__ComputingDevice init_value = MUSE2__COMPUTING_DEVICE__INIT;
  *message = init_value;
}
size_t muse2__computing_device__get_packed_size
                     (const Muse2__ComputingDevice *message)
{
  assert(message->base.descriptor == &muse2__computing_device__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t muse2__computing_device__pack
                     (const Muse2__ComputingDevice *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &muse2__computing_device__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t muse2__computing_device__pack_to_buffer
                     (const Muse2__ComputingDevice *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &muse2__computing_device__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Muse2__ComputingDevice *
       muse2__computing_device__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Muse2__ComputingDevice *)
     protobuf_c_message_unpack (&muse2__computing_device__descriptor,
                                allocator, len, data);
}
void   muse2__computing_device__free_unpacked
                     (Muse2__ComputingDevice *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &muse2__computing_device__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   muse2__dsp__init
                     (Muse2__DSP         *message)
{
  static Muse2__DSP init_value = MUSE2__DSP__INIT;
  *message = init_value;
}
size_t muse2__dsp__get_packed_size
                     (const Muse2__DSP *message)
{
  assert(message->base.descriptor == &muse2__dsp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t muse2__dsp__pack
                     (const Muse2__DSP *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &muse2__dsp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t muse2__dsp__pack_to_buffer
                     (const Muse2__DSP *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &muse2__dsp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Muse2__DSP *
       muse2__dsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Muse2__DSP *)
     protobuf_c_message_unpack (&muse2__dsp__descriptor,
                                allocator, len, data);
}
void   muse2__dsp__free_unpacked
                     (Muse2__DSP *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &muse2__dsp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor muse2__data_collection__field_descriptors[1] =
{
  {
    "collection",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Muse2__DataCollection, n_collection),
    offsetof(Muse2__DataCollection, collection),
    &muse2__data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned muse2__data_collection__field_indices_by_name[] = {
  0,   /* field[0] = collection */
};
static const ProtobufCIntRange muse2__data_collection__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor muse2__data_collection__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "muse2.DataCollection",
  "DataCollection",
  "Muse2__DataCollection",
  "muse2",
  sizeof(Muse2__DataCollection),
  1,
  muse2__data_collection__field_descriptors,
  muse2__data_collection__field_indices_by_name,
  1,  muse2__data_collection__number_ranges,
  (ProtobufCMessageInit) muse2__data_collection__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue muse2__data__datatype__enum_values_by_number[15] =
{
  { "EEG", "MUSE2__DATA__DATATYPE__EEG", 0 },
  { "QUANT", "MUSE2__DATA__DATATYPE__QUANT", 1 },
  { "ACCEL", "MUSE2__DATA__DATATYPE__ACCEL", 2 },
  { "BATTERY", "MUSE2__DATA__DATATYPE__BATTERY", 3 },
  { "VERSION", "MUSE2__DATA__DATATYPE__VERSION", 4 },
  { "CONFIG", "MUSE2__DATA__DATATYPE__CONFIG", 5 },
  { "ANNOTATION", "MUSE2__DATA__DATATYPE__ANNOTATION", 6 },
  { "HISTOGRAM", "MUSE2__DATA__DATATYPE__HISTOGRAM", 7 },
  { "ALGVALUE", "MUSE2__DATA__DATATYPE__ALGVALUE", 8 },
  { "DSP", "MUSE2__DATA__DATATYPE__DSP", 9 },
  { "COMPUTING_DEVICE", "MUSE2__DATA__DATATYPE__COMPUTING_DEVICE", 10 },
  { "EEG_DROPPED", "MUSE2__DATA__DATATYPE__EEG_DROPPED", 11 },
  { "ACC_DROPPED", "MUSE2__DATA__DATATYPE__ACC_DROPPED", 12 },
  { "CALM_APP", "MUSE2__DATA__DATATYPE__CALM_APP", 13 },
  { "CALM_ALG", "MUSE2__DATA__DATATYPE__CALM_ALG", 14 },
};
static const ProtobufCIntRange muse2__data__datatype__value_ranges[] = {
{0, 0},{0, 15}
};
const ProtobufCEnumValueIndex muse2__data__datatype__enum_values_by_name[15] =
{
  { "ACCEL", 2 },
  { "ACC_DROPPED", 12 },
  { "ALGVALUE", 8 },
  { "ANNOTATION", 6 },
  { "BATTERY", 3 },
  { "CALM_ALG", 14 },
  { "CALM_APP", 13 },
  { "COMPUTING_DEVICE", 10 },
  { "CONFIG", 5 },
  { "DSP", 9 },
  { "EEG", 0 },
  { "EEG_DROPPED", 11 },
  { "HISTOGRAM", 7 },
  { "QUANT", 1 },
  { "VERSION", 4 },
};
const ProtobufCEnumDescriptor muse2__data__datatype__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "muse2.Data.Datatype",
  "Datatype",
  "Muse2__Data__Datatype",
  "muse2",
  15,
  muse2__data__datatype__enum_values_by_number,
  15,
  muse2__data__datatype__enum_values_by_name,
  1,
  muse2__data__datatype__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor muse2__data__field_descriptors[3] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Muse2__Data, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "datatype",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Muse2__Data, datatype),
    &muse2__data__datatype__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "config_id",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Muse2__Data, has_config_id),
    offsetof(Muse2__Data, config_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned muse2__data__field_indices_by_name[] = {
  2,   /* field[2] = config_id */
  1,   /* field[1] = datatype */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange muse2__data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor muse2__data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "muse2.Data",
  "Data",
  "Muse2__Data",
  "muse2",
  sizeof(Muse2__Data),
  3,
  muse2__data__field_descriptors,
  muse2__data__field_indices_by_name,
  1,  muse2__data__number_ranges,
  (ProtobufCMessageInit) muse2__data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor muse2__eeg__field_descriptors[3] =
{
  {
    "values",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Muse2__EEG, n_values),
    offsetof(Muse2__EEG, values),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "drl",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Muse2__EEG, has_drl),
    offsetof(Muse2__EEG, drl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ref",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Muse2__EEG, has_ref),
    offsetof(Muse2__EEG, ref),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned muse2__eeg__field_indices_by_name[] = {
  1,   /* field[1] = drl */
  2,   /* field[2] = ref */
  0,   /* field[0] = values */
};
static const ProtobufCIntRange muse2__eeg__number_ranges[2 + 1] =
{
  { 2, 0 },
  { 5, 1 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor muse2__eeg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "muse2.EEG",
  "EEG",
  "Muse2__EEG",
  "muse2",
  sizeof(Muse2__EEG),
  3,
  muse2__eeg__field_descriptors,
  muse2__eeg__field_indices_by_name,
  2,  muse2__eeg__number_ranges,
  (ProtobufCMessageInit) muse2__eeg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor muse2__quantization__field_descriptors[1] =
{
  {
    "values",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Muse2__Quantization, n_values),
    offsetof(Muse2__Quantization, values),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned muse2__quantization__field_indices_by_name[] = {
  0,   /* field[0] = values */
};
static const ProtobufCIntRange muse2__quantization__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor muse2__quantization__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "muse2.Quantization",
  "Quantization",
  "Muse2__Quantization",
  "muse2",
  sizeof(Muse2__Quantization),
  1,
  muse2__quantization__field_descriptors,
  muse2__quantization__field_indices_by_name,
  1,  muse2__quantization__number_ranges,
  (ProtobufCMessageInit) muse2__quantization__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor muse2__accelerometer__field_descriptors[3] =
{
  {
    "acc1",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Muse2__Accelerometer, has_acc1),
    offsetof(Muse2__Accelerometer, acc1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "acc2",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Muse2__Accelerometer, has_acc2),
    offsetof(Muse2__Accelerometer, acc2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "acc3",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Muse2__Accelerometer, has_acc3),
    offsetof(Muse2__Accelerometer, acc3),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned muse2__accelerometer__field_indices_by_name[] = {
  0,   /* field[0] = acc1 */
  1,   /* field[1] = acc2 */
  2,   /* field[2] = acc3 */
};
static const ProtobufCIntRange muse2__accelerometer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor muse2__accelerometer__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "muse2.Accelerometer",
  "Accelerometer",
  "Muse2__Accelerometer",
  "muse2",
  sizeof(Muse2__Accelerometer),
  3,
  muse2__accelerometer__field_descriptors,
  muse2__accelerometer__field_indices_by_name,
  1,  muse2__accelerometer__number_ranges,
  (ProtobufCMessageInit) muse2__accelerometer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue muse2__annotation__format__enum_values_by_number[3] =
{
  { "PLAIN_STRING", "MUSE2__ANNOTATION__FORMAT__PLAIN_STRING", 0 },
  { "JSON", "MUSE2__ANNOTATION__FORMAT__JSON", 1 },
  { "OSC", "MUSE2__ANNOTATION__FORMAT__OSC", 2 },
};
static const ProtobufCIntRange muse2__annotation__format__value_ranges[] = {
{0, 0},{0, 3}
};
const ProtobufCEnumValueIndex muse2__annotation__format__enum_values_by_name[3] =
{
  { "JSON", 1 },
  { "OSC", 2 },
  { "PLAIN_STRING", 0 },
};
const ProtobufCEnumDescriptor muse2__annotation__format__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "muse2.Annotation.Format",
  "Format",
  "Muse2__Annotation__Format",
  "muse2",
  3,
  muse2__annotation__format__enum_values_by_number,
  3,
  muse2__annotation__format__enum_values_by_name,
  1,
  muse2__annotation__format__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const Muse2__Annotation__Format muse2__annotation__event_data_format__default_value = MUSE2__ANNOTATION__FORMAT__PLAIN_STRING;
static const ProtobufCFieldDescriptor muse2__annotation__field_descriptors[5] =
{
  {
    "event_data",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Muse2__Annotation, event_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "event_data_format",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Muse2__Annotation, has_event_data_format),
    offsetof(Muse2__Annotation, event_data_format),
    &muse2__annotation__format__descriptor,
    &muse2__annotation__event_data_format__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "event_type",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Muse2__Annotation, event_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "event_id",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Muse2__Annotation, event_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parent_id",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Muse2__Annotation, parent_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned muse2__annotation__field_indices_by_name[] = {
  0,   /* field[0] = event_data */
  1,   /* field[1] = event_data_format */
  3,   /* field[3] = event_id */
  2,   /* field[2] = event_type */
  4,   /* field[4] = parent_id */
};
static const ProtobufCIntRange muse2__annotation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor muse2__annotation__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "muse2.Annotation",
  "Annotation",
  "Muse2__Annotation",
  "muse2",
  sizeof(Muse2__Annotation),
  5,
  muse2__annotation__field_descriptors,
  muse2__annotation__field_indices_by_name,
  1,  muse2__annotation__number_ranges,
  (ProtobufCMessageInit) muse2__annotation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor muse2__battery__field_descriptors[4] =
{
  {
    "percent_remaining",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Muse2__Battery, has_percent_remaining),
    offsetof(Muse2__Battery, percent_remaining),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "battery_fuel_gauge_millivolts",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Muse2__Battery, has_battery_fuel_gauge_millivolts),
    offsetof(Muse2__Battery, battery_fuel_gauge_millivolts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "battery_adc_millivolts",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Muse2__Battery, has_battery_adc_millivolts),
    offsetof(Muse2__Battery, battery_adc_millivolts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temperature_celsius",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(Muse2__Battery, has_temperature_celsius),
    offsetof(Muse2__Battery, temperature_celsius),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned muse2__battery__field_indices_by_name[] = {
  2,   /* field[2] = battery_adc_millivolts */
  1,   /* field[1] = battery_fuel_gauge_millivolts */
  0,   /* field[0] = percent_remaining */
  3,   /* field[3] = temperature_celsius */
};
static const ProtobufCIntRange muse2__battery__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor muse2__battery__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "muse2.Battery",
  "Battery",
  "Muse2__Battery",
  "muse2",
  sizeof(Muse2__Battery),
  4,
  muse2__battery__field_descriptors,
  muse2__battery__field_indices_by_name,
  1,  muse2__battery__number_ranges,
  (ProtobufCMessageInit) muse2__battery__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor muse2__version__field_descriptors[6] =
{
  {
    "hardware_version",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Muse2__Version, hardware_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "firmware_headset_version",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Muse2__Version, firmware_headset_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "firmware_type",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Muse2__Version, firmware_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "firmware_bootloader_version",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Muse2__Version, firmware_bootloader_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "build_number",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Muse2__Version, build_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "protocol_version",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Muse2__Version, protocol_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned muse2__version__field_indices_by_name[] = {
  4,   /* field[4] = build_number */
  3,   /* field[3] = firmware_bootloader_version */
  1,   /* field[1] = firmware_headset_version */
  2,   /* field[2] = firmware_type */
  0,   /* field[0] = hardware_version */
  5,   /* field[5] = protocol_version */
};
static const ProtobufCIntRange muse2__version__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor muse2__version__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "muse2.Version",
  "Version",
  "Muse2__Version",
  "muse2",
  sizeof(Muse2__Version),
  6,
  muse2__version__field_descriptors,
  muse2__version__field_indices_by_name,
  1,  muse2__version__number_ranges,
  (ProtobufCMessageInit) muse2__version__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor muse2__config__field_descriptors[27] =
{
  {
    "mac_addr",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Muse2__Config, mac_addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial_number",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Muse2__Config, serial_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "preset",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Muse2__Config, preset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "compression_enabled",
    100,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Muse2__Config, has_compression_enabled),
    offsetof(Muse2__Config, compression_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filters_enabled",
    201,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Muse2__Config, has_filters_enabled),
    offsetof(Muse2__Config, filters_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "notch_frequency_hz",
    202,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Muse2__Config, has_notch_frequency_hz),
    offsetof(Muse2__Config, notch_frequency_hz),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eeg_sample_frequency_hz",
    203,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Muse2__Config, has_eeg_sample_frequency_hz),
    offsetof(Muse2__Config, eeg_sample_frequency_hz),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eeg_output_frequency_hz",
    204,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Muse2__Config, has_eeg_output_frequency_hz),
    offsetof(Muse2__Config, eeg_output_frequency_hz),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eeg_samples_bitwidth",
    205,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Muse2__Config, has_eeg_samples_bitwidth),
    offsetof(Muse2__Config, eeg_samples_bitwidth),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eeg_channel_count",
    206,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Muse2__Config, has_eeg_channel_count),
    offsetof(Muse2__Config, eeg_channel_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eeg_channel_layout",
    207,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Muse2__Config, eeg_channel_layout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eeg_downsample",
    208,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Muse2__Config, has_eeg_downsample),
    offsetof(Muse2__Config, eeg_downsample),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eeg_units",
    209,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Muse2__Config, has_eeg_units),
    offsetof(Muse2__Config, eeg_units),
    &muse2__eegunits__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eeg_locations",
    210,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Muse2__Config, n_eeg_locations),
    offsetof(Muse2__Config, eeg_locations),
    &muse2__head_locations__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eeg_conversion_factor",
    211,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Muse2__Config, has_eeg_conversion_factor),
    offsetof(Muse2__Config, eeg_conversion_factor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "afe_gain",
    212,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Muse2__Config, has_afe_gain),
    offsetof(Muse2__Config, afe_gain),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "drlref_data_enabled",
    300,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Muse2__Config, has_drlref_data_enabled),
    offsetof(Muse2__Config, drlref_data_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "drlref_conversion_factor",
    301,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Muse2__Config, has_drlref_conversion_factor),
    offsetof(Muse2__Config, drlref_conversion_factor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "drlref_sample_frequency_hz",
    302,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Muse2__Config, has_drlref_sample_frequency_hz),
    offsetof(Muse2__Config, drlref_sample_frequency_hz),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "acc_data_enabled",
    400,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Muse2__Config, has_acc_data_enabled),
    offsetof(Muse2__Config, acc_data_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "acc_units",
    401,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Muse2__Config, has_acc_units),
    offsetof(Muse2__Config, acc_units),
    &muse2__accelerometer_units__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "acc_conversion_factor",
    402,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Muse2__Config, has_acc_conversion_factor),
    offsetof(Muse2__Config, acc_conversion_factor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "acc_sample_frequency_hz",
    403,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Muse2__Config, has_acc_sample_frequency_hz),
    offsetof(Muse2__Config, acc_sample_frequency_hz),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "battery_data_enabled",
    500,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Muse2__Config, has_battery_data_enabled),
    offsetof(Muse2__Config, battery_data_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "battery_percent_remaining",
    501,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Muse2__Config, has_battery_percent_remaining),
    offsetof(Muse2__Config, battery_percent_remaining),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "battery_millivolts",
    502,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Muse2__Config, has_battery_millivolts),
    offsetof(Muse2__Config, battery_millivolts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_data_enabled",
    600,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Muse2__Config, has_error_data_enabled),
    offsetof(Muse2__Config, error_data_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned muse2__config__field_indices_by_name[] = {
  21,   /* field[21] = acc_conversion_factor */
  19,   /* field[19] = acc_data_enabled */
  22,   /* field[22] = acc_sample_frequency_hz */
  20,   /* field[20] = acc_units */
  15,   /* field[15] = afe_gain */
  23,   /* field[23] = battery_data_enabled */
  25,   /* field[25] = battery_millivolts */
  24,   /* field[24] = battery_percent_remaining */
  3,   /* field[3] = compression_enabled */
  17,   /* field[17] = drlref_conversion_factor */
  16,   /* field[16] = drlref_data_enabled */
  18,   /* field[18] = drlref_sample_frequency_hz */
  9,   /* field[9] = eeg_channel_count */
  10,   /* field[10] = eeg_channel_layout */
  14,   /* field[14] = eeg_conversion_factor */
  11,   /* field[11] = eeg_downsample */
  13,   /* field[13] = eeg_locations */
  7,   /* field[7] = eeg_output_frequency_hz */
  6,   /* field[6] = eeg_sample_frequency_hz */
  8,   /* field[8] = eeg_samples_bitwidth */
  12,   /* field[12] = eeg_units */
  26,   /* field[26] = error_data_enabled */
  4,   /* field[4] = filters_enabled */
  0,   /* field[0] = mac_addr */
  5,   /* field[5] = notch_frequency_hz */
  2,   /* field[2] = preset */
  1,   /* field[1] = serial_number */
};
static const ProtobufCIntRange muse2__config__number_ranges[7 + 1] =
{
  { 1, 0 },
  { 100, 3 },
  { 201, 4 },
  { 300, 16 },
  { 400, 19 },
  { 500, 23 },
  { 600, 26 },
  { 0, 27 }
};
const ProtobufCMessageDescriptor muse2__config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "muse2.Config",
  "Config",
  "Muse2__Config",
  "muse2",
  sizeof(Muse2__Config),
  27,
  muse2__config__field_descriptors,
  muse2__config__field_indices_by_name,
  7,  muse2__config__number_ranges,
  (ProtobufCMessageInit) muse2__config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor muse2__eeg__dropped_samples__field_descriptors[1] =
{
  {
    "num",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Muse2__EEGDroppedSamples, has_num),
    offsetof(Muse2__EEGDroppedSamples, num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned muse2__eeg__dropped_samples__field_indices_by_name[] = {
  0,   /* field[0] = num */
};
static const ProtobufCIntRange muse2__eeg__dropped_samples__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor muse2__eeg__dropped_samples__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "muse2.EEG_DroppedSamples",
  "EEGDroppedSamples",
  "Muse2__EEGDroppedSamples",
  "muse2",
  sizeof(Muse2__EEGDroppedSamples),
  1,
  muse2__eeg__dropped_samples__field_descriptors,
  muse2__eeg__dropped_samples__field_indices_by_name,
  1,  muse2__eeg__dropped_samples__number_ranges,
  (ProtobufCMessageInit) muse2__eeg__dropped_samples__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor muse2__acc__dropped_samples__field_descriptors[1] =
{
  {
    "num",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Muse2__ACCDroppedSamples, has_num),
    offsetof(Muse2__ACCDroppedSamples, num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned muse2__acc__dropped_samples__field_indices_by_name[] = {
  0,   /* field[0] = num */
};
static const ProtobufCIntRange muse2__acc__dropped_samples__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor muse2__acc__dropped_samples__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "muse2.ACC_DroppedSamples",
  "ACCDroppedSamples",
  "Muse2__ACCDroppedSamples",
  "muse2",
  sizeof(Muse2__ACCDroppedSamples),
  1,
  muse2__acc__dropped_samples__field_descriptors,
  muse2__acc__dropped_samples__field_indices_by_name,
  1,  muse2__acc__dropped_samples__number_ranges,
  (ProtobufCMessageInit) muse2__acc__dropped_samples__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor muse2__computing_device__field_descriptors[11] =
{
  {
    "os_type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Muse2__ComputingDevice, os_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "os_version",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Muse2__ComputingDevice, os_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hardware_model_name",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Muse2__ComputingDevice, hardware_model_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hardware_model_id",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Muse2__ComputingDevice, hardware_model_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "processor_name",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Muse2__ComputingDevice, processor_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "processor_speed",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Muse2__ComputingDevice, processor_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "number_of_processors",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Muse2__ComputingDevice, has_number_of_processors),
    offsetof(Muse2__ComputingDevice, number_of_processors),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "memory_size",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Muse2__ComputingDevice, memory_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bluetooth_version",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Muse2__ComputingDevice, bluetooth_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_zone",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Muse2__ComputingDevice, time_zone),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_zone_offset_seconds",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(Muse2__ComputingDevice, has_time_zone_offset_seconds),
    offsetof(Muse2__ComputingDevice, time_zone_offset_seconds),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned muse2__computing_device__field_indices_by_name[] = {
  8,   /* field[8] = bluetooth_version */
  3,   /* field[3] = hardware_model_id */
  2,   /* field[2] = hardware_model_name */
  7,   /* field[7] = memory_size */
  6,   /* field[6] = number_of_processors */
  0,   /* field[0] = os_type */
  1,   /* field[1] = os_version */
  4,   /* field[4] = processor_name */
  5,   /* field[5] = processor_speed */
  9,   /* field[9] = time_zone */
  10,   /* field[10] = time_zone_offset_seconds */
};
static const ProtobufCIntRange muse2__computing_device__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor muse2__computing_device__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "muse2.ComputingDevice",
  "ComputingDevice",
  "Muse2__ComputingDevice",
  "muse2",
  sizeof(Muse2__ComputingDevice),
  11,
  muse2__computing_device__field_descriptors,
  muse2__computing_device__field_indices_by_name,
  1,  muse2__computing_device__number_ranges,
  (ProtobufCMessageInit) muse2__computing_device__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor muse2__dsp__field_descriptors[4] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Muse2__DSP, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "float_array",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Muse2__DSP, n_float_array),
    offsetof(Muse2__DSP, float_array),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "int_array",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Muse2__DSP, n_int_array),
    offsetof(Muse2__DSP, int_array),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Muse2__DSP, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned muse2__dsp__field_indices_by_name[] = {
  1,   /* field[1] = float_array */
  2,   /* field[2] = int_array */
  0,   /* field[0] = type */
  3,   /* field[3] = version */
};
static const ProtobufCIntRange muse2__dsp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor muse2__dsp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "muse2.DSP",
  "DSP",
  "Muse2__DSP",
  "muse2",
  sizeof(Muse2__DSP),
  4,
  muse2__dsp__field_descriptors,
  muse2__dsp__field_indices_by_name,
  1,  muse2__dsp__number_ranges,
  (ProtobufCMessageInit) muse2__dsp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue muse2__head_locations__enum_values_by_number[81] =
{
  { "NZ", "MUSE2__HEAD_LOCATIONS__NZ", 1 },
  { "FP1", "MUSE2__HEAD_LOCATIONS__FP1", 2 },
  { "FPZ", "MUSE2__HEAD_LOCATIONS__FPZ", 3 },
  { "FP2", "MUSE2__HEAD_LOCATIONS__FP2", 4 },
  { "AF7", "MUSE2__HEAD_LOCATIONS__AF7", 5 },
  { "AF3", "MUSE2__HEAD_LOCATIONS__AF3", 6 },
  { "AFZ", "MUSE2__HEAD_LOCATIONS__AFZ", 7 },
  { "AF4", "MUSE2__HEAD_LOCATIONS__AF4", 8 },
  { "AF8", "MUSE2__HEAD_LOCATIONS__AF8", 9 },
  { "F9", "MUSE2__HEAD_LOCATIONS__F9", 10 },
  { "F7", "MUSE2__HEAD_LOCATIONS__F7", 11 },
  { "F5", "MUSE2__HEAD_LOCATIONS__F5", 12 },
  { "F3", "MUSE2__HEAD_LOCATIONS__F3", 13 },
  { "F1", "MUSE2__HEAD_LOCATIONS__F1", 14 },
  { "FZ", "MUSE2__HEAD_LOCATIONS__FZ", 15 },
  { "F2", "MUSE2__HEAD_LOCATIONS__F2", 16 },
  { "F4", "MUSE2__HEAD_LOCATIONS__F4", 17 },
  { "F6", "MUSE2__HEAD_LOCATIONS__F6", 18 },
  { "F8", "MUSE2__HEAD_LOCATIONS__F8", 19 },
  { "F10", "MUSE2__HEAD_LOCATIONS__F10", 20 },
  { "FT9", "MUSE2__HEAD_LOCATIONS__FT9", 21 },
  { "FT7", "MUSE2__HEAD_LOCATIONS__FT7", 22 },
  { "FC5", "MUSE2__HEAD_LOCATIONS__FC5", 23 },
  { "FC3", "MUSE2__HEAD_LOCATIONS__FC3", 24 },
  { "FC1", "MUSE2__HEAD_LOCATIONS__FC1", 25 },
  { "FCZ", "MUSE2__HEAD_LOCATIONS__FCZ", 26 },
  { "FC2", "MUSE2__HEAD_LOCATIONS__FC2", 27 },
  { "FC4", "MUSE2__HEAD_LOCATIONS__FC4", 28 },
  { "FC6", "MUSE2__HEAD_LOCATIONS__FC6", 29 },
  { "FT8", "MUSE2__HEAD_LOCATIONS__FT8", 30 },
  { "FT10", "MUSE2__HEAD_LOCATIONS__FT10", 31 },
  { "A1", "MUSE2__HEAD_LOCATIONS__A1", 32 },
  { "T9", "MUSE2__HEAD_LOCATIONS__T9", 33 },
  { "T7", "MUSE2__HEAD_LOCATIONS__T7", 34 },
  { "C5", "MUSE2__HEAD_LOCATIONS__C5", 35 },
  { "C3", "MUSE2__HEAD_LOCATIONS__C3", 36 },
  { "C1", "MUSE2__HEAD_LOCATIONS__C1", 37 },
  { "CZ", "MUSE2__HEAD_LOCATIONS__CZ", 38 },
  { "C2", "MUSE2__HEAD_LOCATIONS__C2", 39 },
  { "C4", "MUSE2__HEAD_LOCATIONS__C4", 40 },
  { "C6", "MUSE2__HEAD_LOCATIONS__C6", 41 },
  { "T8", "MUSE2__HEAD_LOCATIONS__T8", 42 },
  { "T10", "MUSE2__HEAD_LOCATIONS__T10", 43 },
  { "A2", "MUSE2__HEAD_LOCATIONS__A2", 44 },
  { "TP9", "MUSE2__HEAD_LOCATIONS__TP9", 45 },
  { "TP7", "MUSE2__HEAD_LOCATIONS__TP7", 46 },
  { "CP5", "MUSE2__HEAD_LOCATIONS__CP5", 47 },
  { "CP3", "MUSE2__HEAD_LOCATIONS__CP3", 48 },
  { "CP1", "MUSE2__HEAD_LOCATIONS__CP1", 49 },
  { "CPZ", "MUSE2__HEAD_LOCATIONS__CPZ", 50 },
  { "CP2", "MUSE2__HEAD_LOCATIONS__CP2", 51 },
  { "CP4", "MUSE2__HEAD_LOCATIONS__CP4", 52 },
  { "CP6", "MUSE2__HEAD_LOCATIONS__CP6", 53 },
  { "TP8", "MUSE2__HEAD_LOCATIONS__TP8", 54 },
  { "TP10", "MUSE2__HEAD_LOCATIONS__TP10", 55 },
  { "P9", "MUSE2__HEAD_LOCATIONS__P9", 56 },
  { "P7", "MUSE2__HEAD_LOCATIONS__P7", 57 },
  { "P5", "MUSE2__HEAD_LOCATIONS__P5", 58 },
  { "P3", "MUSE2__HEAD_LOCATIONS__P3", 59 },
  { "P1", "MUSE2__HEAD_LOCATIONS__P1", 60 },
  { "PZ", "MUSE2__HEAD_LOCATIONS__PZ", 61 },
  { "P2", "MUSE2__HEAD_LOCATIONS__P2", 62 },
  { "P4", "MUSE2__HEAD_LOCATIONS__P4", 63 },
  { "P6", "MUSE2__HEAD_LOCATIONS__P6", 64 },
  { "P8", "MUSE2__HEAD_LOCATIONS__P8", 65 },
  { "P10", "MUSE2__HEAD_LOCATIONS__P10", 66 },
  { "PO7", "MUSE2__HEAD_LOCATIONS__PO7", 67 },
  { "PO3", "MUSE2__HEAD_LOCATIONS__PO3", 68 },
  { "POZ", "MUSE2__HEAD_LOCATIONS__POZ", 69 },
  { "PO4", "MUSE2__HEAD_LOCATIONS__PO4", 70 },
  { "PO8", "MUSE2__HEAD_LOCATIONS__PO8", 71 },
  { "O1", "MUSE2__HEAD_LOCATIONS__O1", 72 },
  { "OZ", "MUSE2__HEAD_LOCATIONS__OZ", 73 },
  { "O2", "MUSE2__HEAD_LOCATIONS__O2", 74 },
  { "IZ", "MUSE2__HEAD_LOCATIONS__IZ", 75 },
  { "AUX1", "MUSE2__HEAD_LOCATIONS__AUX1", 76 },
  { "AUX2", "MUSE2__HEAD_LOCATIONS__AUX2", 77 },
  { "AUX3", "MUSE2__HEAD_LOCATIONS__AUX3", 78 },
  { "AUX4", "MUSE2__HEAD_LOCATIONS__AUX4", 79 },
  { "MUSE_LEFT_AUX", "MUSE2__HEAD_LOCATIONS__MUSE_LEFT_AUX", 80 },
  { "MUSE_RIGHT_AUX", "MUSE2__HEAD_LOCATIONS__MUSE_RIGHT_AUX", 81 },
};
static const ProtobufCIntRange muse2__head_locations__value_ranges[] = {
{1, 0},{0, 81}
};
const ProtobufCEnumValueIndex muse2__head_locations__enum_values_by_name[81] =
{
  { "A1", 31 },
  { "A2", 43 },
  { "AF3", 5 },
  { "AF4", 7 },
  { "AF7", 4 },
  { "AF8", 8 },
  { "AFZ", 6 },
  { "AUX1", 75 },
  { "AUX2", 76 },
  { "AUX3", 77 },
  { "AUX4", 78 },
  { "C1", 36 },
  { "C2", 38 },
  { "C3", 35 },
  { "C4", 39 },
  { "C5", 34 },
  { "C6", 40 },
  { "CP1", 48 },
  { "CP2", 50 },
  { "CP3", 47 },
  { "CP4", 51 },
  { "CP5", 46 },
  { "CP6", 52 },
  { "CPZ", 49 },
  { "CZ", 37 },
  { "F1", 13 },
  { "F10", 19 },
  { "F2", 15 },
  { "F3", 12 },
  { "F4", 16 },
  { "F5", 11 },
  { "F6", 17 },
  { "F7", 10 },
  { "F8", 18 },
  { "F9", 9 },
  { "FC1", 24 },
  { "FC2", 26 },
  { "FC3", 23 },
  { "FC4", 27 },
  { "FC5", 22 },
  { "FC6", 28 },
  { "FCZ", 25 },
  { "FP1", 1 },
  { "FP2", 3 },
  { "FPZ", 2 },
  { "FT10", 30 },
  { "FT7", 21 },
  { "FT8", 29 },
  { "FT9", 20 },
  { "FZ", 14 },
  { "IZ", 74 },
  { "MUSE_LEFT_AUX", 79 },
  { "MUSE_RIGHT_AUX", 80 },
  { "NZ", 0 },
  { "O1", 71 },
  { "O2", 73 },
  { "OZ", 72 },
  { "P1", 59 },
  { "P10", 65 },
  { "P2", 61 },
  { "P3", 58 },
  { "P4", 62 },
  { "P5", 57 },
  { "P6", 63 },
  { "P7", 56 },
  { "P8", 64 },
  { "P9", 55 },
  { "PO3", 67 },
  { "PO4", 69 },
  { "PO7", 66 },
  { "PO8", 70 },
  { "POZ", 68 },
  { "PZ", 60 },
  { "T10", 42 },
  { "T7", 33 },
  { "T8", 41 },
  { "T9", 32 },
  { "TP10", 54 },
  { "TP7", 45 },
  { "TP8", 53 },
  { "TP9", 44 },
};
const ProtobufCEnumDescriptor muse2__head_locations__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "muse2.HeadLocations",
  "HeadLocations",
  "Muse2__HeadLocations",
  "muse2",
  81,
  muse2__head_locations__enum_values_by_number,
  81,
  muse2__head_locations__enum_values_by_name,
  1,
  muse2__head_locations__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue muse2__eegunits__enum_values_by_number[2] =
{
  { "EEG_MICROVOLTS", "MUSE2__EEGUNITS__EEG_MICROVOLTS", 1 },
  { "EEG_MUSE1_RAW", "MUSE2__EEGUNITS__EEG_MUSE1_RAW", 2 },
};
static const ProtobufCIntRange muse2__eegunits__value_ranges[] = {
{1, 0},{0, 2}
};
const ProtobufCEnumValueIndex muse2__eegunits__enum_values_by_name[2] =
{
  { "EEG_MICROVOLTS", 0 },
  { "EEG_MUSE1_RAW", 1 },
};
const ProtobufCEnumDescriptor muse2__eegunits__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "muse2.EEGUnits",
  "EEGUnits",
  "Muse2__EEGUnits",
  "muse2",
  2,
  muse2__eegunits__enum_values_by_number,
  2,
  muse2__eegunits__enum_values_by_name,
  1,
  muse2__eegunits__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue muse2__accelerometer_units__enum_values_by_number[2] =
{
  { "ACC_GFORCE", "MUSE2__ACCELEROMETER_UNITS__ACC_GFORCE", 1 },
  { "ACC_MUSE1_RAW", "MUSE2__ACCELEROMETER_UNITS__ACC_MUSE1_RAW", 2 },
};
static const ProtobufCIntRange muse2__accelerometer_units__value_ranges[] = {
{1, 0},{0, 2}
};
const ProtobufCEnumValueIndex muse2__accelerometer_units__enum_values_by_name[2] =
{
  { "ACC_GFORCE", 0 },
  { "ACC_MUSE1_RAW", 1 },
};
const ProtobufCEnumDescriptor muse2__accelerometer_units__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "muse2.AccelerometerUnits",
  "AccelerometerUnits",
  "Muse2__AccelerometerUnits",
  "muse2",
  2,
  muse2__accelerometer_units__enum_values_by_number,
  2,
  muse2__accelerometer_units__enum_values_by_name,
  1,
  muse2__accelerometer_units__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
